import os
basedir = os.path.abspath(os.path.dirname(__file__))

SQLALCHEMY_TRACK_MODIFICATIONS = False # https://stackoverflow.com/questions/33738467/how-do-i-know-if-i-can-disable-sqlalchemy-track-modifications
SQLALCHEMY_DATABASE_PATH = os.path.join(basedir, 'matador.db')
SQLALCHEMY_DATABASE_URI = 'sqlite:///' + SQLALCHEMY_DATABASE_PATH
SQLALCHEMY_MIGRATE_REPO = os.path.join(basedir, 'db_migrations') 
WTF_CSRF_ENABLED = True
SECRET_KEY = 'you-will-never-guess'

# BASE COLORS
COLOR_PRIMARY = '#f7ce3e'
COLOR_PRIMARY_DARK = '#dcaf09'
COLOR_PRIMARY_DARKEST = '#ab8807'
COLOR_ACCENT = '#c5c1c0'
COLOR_SECONDARY = '#1a2930'
COLOR_SECONDARY_ALPHA = '#991a2930'
COLOR_SECONDARY_DARK = '#0e161a'
COLOR_SECONDARY_DARK_ALPHA = '#990e161a'

# LIGHT THEME COLORS
COLOR_ACCENT_PRIMARY_DARK = '#212124'
COLOR_ACCENT_SECONDARY_DARK = '#444447'
COLOR_BACKGROUND_LIGHTEST = '#f4f4f7'
COLOR_BACKGROUND_LIGHTEST_ALPHA = '#99f4f4f7'
COLOR_BACKGROUND_LIGHT = '#ffffff'
COLOR_BACKGROUND_LIGHT_ALPHA = '#99ffffff'

# DARK THEME COLORS
COLOR_ACCENT_PRIMARY_LIGHT = '#ffffff'
COLOR_ACCENT_SECONDARY_LIGHT = '#9a9c9a'
COLOR_BACKGROUND_DARKEST = '#212124'
COLOR_BACKGROUND_DARKEST_ALPHA = '#99212124'
COLOR_BACKGROUND_DARK = '#303032'
COLOR_BACKGROUND_DARK_ALPHA = '#99303032'